### ISSUE TITLE
no circular error when there is no base case

### ISSUE THREAD

**Issue by georgiepayne** [stchang/450lang#10]
**Example That Shows the Bug**
```
(bind/rec
 (circular
  (fn (x)
      (circular (+ x 1))))
 (circular 1))
```

**Expected Result**
CIRCULAR-ERROR

**Actual (Incorrect) Result**
program runs infinitely

**Additional Information**
There is no base case in the bind/rec and the data definitions in hw13 say this would be a circular error

**Comment by stchang** [comment]
Good attempt! But unfortunately, this example is working as intended and is not a bug.

A "circular error" occurs when trying to reference a binding recursively before the definition is completely defined. An example of this in Racket would be `(letrec ([x x]) x)` which results in an error: ` x: undefined; cannot use before initialization`. A similar example in `450lang` `(bind/rec [x x] x)` correctly evaluates to `(circular-err 'x)`

But the given example does not try to reference `x` until the body of the `bind/rec`, which is allowed. So the program is just an infinite loop, which is a valid program (in almost every programming language, not just `450lang`)!

(In the future please use the markdown verbatim tag (```) to format code so it's easier to read)
