### ISSUE TITLE
if expressions failing when numbers are used as opposed to booleans

### ISSUE THREAD

**Issue by p-laskey** [stchang/450lang#12]
**Example That Shows the Bug**
(chk= (if 10 'yes 'no) 'yes)

**Expected Result**
'yes ;; 10 is evaluated as true, therefore return 'yes)

**Actual (Incorrect) Result**
(type-error 'if) ;; Implies that the example is not a boolean expression 

**Additional Information**
This implies the implementation of "if" implements only booleans unlike other langauges

**Comment by stchang** [comment]
Hi thanks for the report! 

But this example is not a bug because `if` is not in the `450lang` language. (Also a little confused about the given "Actual" result since that is not a valid `450lang` `Result`)
