### ISSUE TITLE
undefined-var-err accepting incorrect inputs

### ISSUE THREAD

**Issue by p-laskey** [stchang/450lang#13]
**Example That Shows the Bug**
undefined-var-err("incorrect input")

**Expected Result**
Error ;; Should only accept 'symbols

**Actual (Incorrect) Result**
undefined-var-err: "incorrect input"

**Additional Information**
 The error constructed with an incorrect type, something that is not a symbol

**Comment by stchang** [comment]
Hi thanks for the report, but it's unclear what is being reported. The Example should be a valid `450lang` program, and the Expected/Actual results need to be valid according to the `450Lang` data definition. Please update the report with this information

**Comment by stchang** [comment]
Closing this as not a bug. Reopen another issue if you wish to continue discussion
