### ISSUE TITLE
Division by zero does not throw an error

### ISSUE THREAD

**Issue by kaifkhalifa** [stchang/450lang#15]
**Example That Shows the Bug**
#lang 450lang

(/ 1 0)

**Expected Result**
A runtime error indicating that division by zero is not allowed.
**Actual (Incorrect) Result**
NaN or undefined behavior.

**Additional Information**
none

**Comment by stchang** [comment]
Did you really get `NaN`? When I run the example, I get `/: division by zero`

The `450lang` specification says that `/` works like Racket's `/` so this seems to be the correct behavior

**Comment by kaifkhalifa** [comment]
Thank you for checking into this. I apologize for the confusion. When I initially ran the example, I must have misinterpreted the output. After re-testing, I see that / does indeed produce a “division by zero” error as documented, which matches your results. It appears this is not a bug after all.

I appreciate your clarification and will close this issue.
