### ISSUE TITLE
Non-Terminating insert on Sorted Lists

### ISSUE THREAD

**Issue by kaifkhalifa** [stchang/450lang#16]
**Example That Shows the Bug**
#lang 450lang

(insert >= 3 (li 5 4 3))

**Expected Result**
(li 5 4 3 3)
**Actual (Incorrect) Result**
Non-termination or infinite recursion.
**Additional Information**
none

**Comment by stchang** [comment]
This report is incomplete unless the definition of `insert` is given. (But you might be misunderstanding the assignment. We are not looking for bugs in your hw. We are looking for bugs in the implementation of `450lang`)
