### ISSUE TITLE
Missing round Function Support

### ISSUE THREAD

**Issue by kaifkhalifa** [stchang/450lang#17]
**Example That Shows the Bug**
#lang 450lang

(round 4.6)

**Expected Result**
5 (correct rounding to the nearest integer).
**Actual (Incorrect) Result**
undefined-var-err 'round
**Additional Information**
none

**Comment by stchang** [comment]
`450lang` does not support `round` at this moment. I would be nice if it did, but this would be a feature request, not a bug
