### ISSUE TITLE
deg->rad Fails for Negative Inputs

### ISSUE THREAD

**Issue by kaifkhalifa** [stchang/450lang#18]
**Example That Shows the Bug**
#lang 450lang

(deg->rad -45)

**Expected Result**
A valid negative radian value (e.g., -π/4).
**Actual (Incorrect) Result**

**Additional Information**
Either an error or incorrect numeric output (e.g., not matching -π/4).

**Comment by stchang** [comment]
Hi thanks for the reports, but you are not understanding the assignment (this is not the place to report bugs in your hw), so please stop opening issue tickets until we can clarify offline

**Comment by kaifkhalifa** [comment]
ohh okay I see, sorry for the misunderstanding. Let me try again
