### ISSUE TITLE
(1st) applied to empty list does not produce the documented error

### ISSUE THREAD

**Issue by kaifkhalifa** [stchang/450lang#19]
**Example That Shows the Bug**
#lang 450lang

(1st mt)

**Expected Result**
I think according to the documentation (or standard logic), (1st mt) should produce (INDEX-ERROR 1st) or some known error indicating you can’t take the first element of an empty list.
**Actual (Incorrect) Result**
(undefined-var-err 'mt) or some other unrelated error message.
**Additional Information**
I would expect (1st) to consistently produce an INDEX-ERROR when applied to an empty list. Getting an undefined-var error suggests a bug in error handling.

I hope this is more in scope of the extra credit and the effort counts!

**Comment by stchang** [comment]
The "Actual Result" is not correct. Have you run your examples? You should not be guessing

**Comment by stchang** [comment]
But this is not a bug, because it does what Racket does, which is what it is supposed to
