### ISSUE TITLE
Append Unable to Work

### ISSUE THREAD

**Issue by p-laskey** [stchang/450lang#21]
**Example That Shows the Bug**
(chk= (append '(1 2 3)) '(1 2 3))

**Expected Result**
'(1 2 3)

**Actual (Incorrect) Result**
(undefined-var-error 'append)
(undefined-var-error 'quote)

**Additional Information**
This could be that append simply is not added into 450lang since it's giving the undefined-var-error, but still demonstrates a function that will not work in the given language that ordinarily works as intended in regular Racket

**Comment by stchang** [comment]
Hi, neither `append` nor `quote` are in `450lang` so the program's behavior is working as intended.
