### ISSUE TITLE
Undefined Variable Errors for Core Functions and Mismatched Test Expectations

### ISSUE THREAD

**Issue by fmisha74** [stchang/450lang#5]
**Example That Shows the Bug**

#lang 450lang

;; Test cases demonstrating the issue
(chk= (nan? 42) #f)                      ;; Should return `#f` since 42 is a number
(chk= (450= 1 1) #t)                     ;; Should return `#t` since 1 equals 1
(chk= (undefined-var-err? undefined) 'TRUE) ;; Check if `undefined-var-err?` correctly handles an undefined variable

**Expected Result**

1. (nan? 42) should return #f because 42 is a valid number.
2. (450= 1 1) should return #t because 1 equals 1.
3. (undefined-var-err? undefined) should return 'TRUE.

**Actual (Incorrect) Result**
1. (nan? 42) throws (undefined-var-err 'nan?) instead of returning #f.
2. (450= 1 1) throws (undefined-var-err '450=) instead of returning #t.
3. (undefined-var-err? undefined) throws (undefined-var-err 'undefined-var-err?) instead of returning 'TRUE.

**Additional Information**

This issue occurs because the functions nan?, 450=, and undefined-var-err? are not properly bound in the INIT-ENV environment, leading to undefined-var-err exceptions.

**Comment by stchang** [comment]
Hi thanks for the report, but this issue describes multiple potential issues, so please resubmit each one as a separate issue. Thank you
