### ISSUE TITLE
Bug Report 1: Undefined Variable Error for nan?

### ISSUE THREAD

**Issue by fmisha74** [stchang/450lang#7]
**Example That Shows the Bug**

 #lang 450lang

(chk= (nan? 42) #f) ;; Should check if 42 is a number

**Expected Result**

The program should return #f because 42 is a valid number.

**Actual (Incorrect) Result**

The program throws (undefined-var-err 'nan?).

**Additional Information**

The function nan? is not properly bound in the INIT-ENV environment.

Add any other information about the problem here.

**Comment by stchang** [comment]
Hi thanks for the report, but this is not a bug.

Identifiers in `450lang` are case sensitive, so `NaN?` is a predicate in the language, but `nan?` is not.

```
> (NaN? (- 1 "1"))
#t
```
