### ISSUE TITLE
Bug Report 2: Undefined Variable Error for 450=

### ISSUE THREAD

**Issue by fmisha74** [stchang/450lang#8]
**Example That Shows the Bug**

#lang 450lang

(chk= (450= 1 1) #t) ;; Should compare equality

**Expected Result**
The program should return #t because 1 equals 1

**Actual (Incorrect) Result**
The program throws (undefined-var-err '450=).

**Additional Information**

The function 450= is not properly bound in the INIT-ENV environment.

Add any other information about the problem here.

**Comment by stchang** [comment]
Hi thanks for the report, but this is not a bug because `450=` is an internal function and is not supposed to be something that users see, so is not in the initial environment. Programmers can only write what is allowed by the `450Expr` data definition
