### ISSUE TITLE
Bug Report 3: Undefined Variable Error for undefined-var-err?

### ISSUE THREAD

**Issue by fmisha74** [stchang/450lang#9]
**Example That Shows the Bug**

#lang 450lang

(chk= (undefined-var-err? undefined) 'TRUE) ;; Should check for undefined variable errors

**Expected Result**

The program should return 'TRUE because undefined is not bound

**Actual (Incorrect) Result**

The program throws (undefined-var-err 'undefined-var-err?)

**Additional Information**

The function undefined-var-err? is not properly bound in the INIT-ENV environment.

Add any other information about the problem here.

**Comment by stchang** [comment]
Similar to #7 and #8, this is also not a bug.

The available predicate is `UNDEFINED-ERROR?`
```
> (UNDEFINED-ERROR? X)
#t
```
